apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "quickstart-pipelines.fullname" . }}-source
  labels:
    {{- include "quickstart-pipelines.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.workspace.storageSize }}
  {{- if .Values.workspace.storageClass }}
  storageClassName: {{ .Values.workspace.storageClass }}
  {{- end }}
{{- if (include "quickstart-pipelines.needsConfigWorkspace" .) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "quickstart-pipelines.fullname" . }}-config
  labels:
    {{- include "quickstart-pipelines.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
  {{- if .Values.workspace.storageClass }}
  storageClassName: {{ .Values.workspace.storageClass }}
  {{- end }}
{{- end }}
