{{- if and .Values.application .Values.application.assetRepository .Values.application.assetRepository.url }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "quickstart-gitops.fullname" . }}
  namespace: {{ .Values.argocd.namespace }}
  labels:
    {{- include "quickstart-gitops.labels" . | nindent 4 }}
  {{- with (include "quickstart-gitops.konveyorAnnotations" . | fromYaml) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  {{- if .Values.appProject.enabled }}
  project: {{ include "quickstart-gitops.fullname" . }}
  {{- else }}
  project: {{ .Values.argocd.project }}
  {{- end }}
  source:
    repoURL: {{ .Values.application.assetRepository.url }}
    targetRevision: {{ include "quickstart-gitops.targetRevision" . }}
    path: {{ include "quickstart-gitops.sourcePath" . }}
  destination:
    server: {{ .Values.argocd.destinationServer }}
    namespace: {{ .Values.targetNamespace }}
  syncPolicy:
    {{- if .Values.argocd.syncPolicy.automated }}
    automated:
      {{- toYaml .Values.argocd.syncPolicy.automated | nindent 6 }}
    {{- end }}
    {{- with .Values.argocd.syncPolicy.syncOptions }}
    syncOptions:
      {{- toYaml . | nindent 6 }}
    {{- end }}
{{- end }}
