{{- if and .Values.appProject.enabled .Values.application .Values.application.assetRepository .Values.application.assetRepository.url }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ include "quickstart-gitops.fullname" . }}
  namespace: {{ .Values.argocd.namespace }}
  labels:
    {{- include "quickstart-gitops.labels" . | nindent 4 }}
  {{- with (include "quickstart-gitops.konveyorAnnotations" . | fromYaml) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  description: ArgoCD project for {{ include "quickstart-gitops.fullname" . }}
  sourceRepos:
    - {{ .Values.application.assetRepository.url | quote }}
    {{- range .Values.appProject.additionalSourceRepos }}
    - {{ . | quote }}
    {{- end }}
  destinations:
    - namespace: {{ .Values.targetNamespace }}
      server: {{ .Values.argocd.destinationServer }}
    {{- range .Values.appProject.additionalDestinations }}
    - namespace: {{ .namespace }}
      server: {{ .server | default "https://kubernetes.default.svc" }}
    {{- end }}
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
{{- end }}
