application:
    archetypes:
        - Java
    assetRepository:
        branch: main
        kind: git
        path: ""
        tag: ""
        url: https://github.com/jortel/hack.git
    binary: ""
    businessService: ""
    contributors: []
    name: micro-services-demo
    owner: ""
    repository:
        branch: konveyor
        kind: git
        path: orders
        tag: ""
        url: https://github.com/rromannissen/rhoar-microservices-demo.git
manifest: {}
tags:
    - Configuration Management=Spring Properties
    - Integration=Micrometer
    - Inversion of Control=Spring DI
    - MVC=Spring MVC
    - Observability=Spring Boot Actuator
    - Other=Properties
    - Persistence=JPA named queries
    - Persistence=Spring Data JPA
    - Web=Spring Web
    - Language=Java
    - Framework=Spring
    - Framework=Spring Boot
    - Tooling=Maven
    - Language=PLSQL
    - Language=TSQL
    - Language=PLpgSQL
    - Language=SQLPL
    - Store=JPA named queries
    - Execute=Spring DI
    - Embedded=Spring MVC
    - Embedded=Properties
    - Store=Spring Data JPA
    - Embedded=Spring Data JPA
    - View=Spring Web
    - Embedded=Spring Web
    - Sustain=Spring Boot Actuator
    - Embedded=Spring Boot Actuator
    - Java EE=JPA named queries
    - Embedded=Spring DI
    - Embedded=Micrometer
    - View=Spring MVC
    - Execute=Micrometer
    - Sustain=Properties
    - Sustain=Application Properties File
    - Embedded=Application Properties File
    - Sustain=Spring Boot Component Scan
    - Embedded=Spring Boot Component Scan
    - Sustain=Spring Boot Auto-configuration
    - Configuration Management=Application Properties File
    - Configuration Management=Spring Boot Auto-configuration
    - Sustain=Spring Properties
    - Embedded=Spring Boot Auto-configuration
    - Sustain=Spring Boot Configuration
    - Configuration Management=Spring Boot Configuration
    - Embedded=Spring Properties
    - Configuration Management=Spring Boot Component Scan
    - Embedded=Spring Boot Configuration
