application:
    archetypes:
        - Test-0
    binary: ""
    businessService: ""
    contributors: []
    name: TestPlatform
    owner: ""
    repository:
        branch: ""
        kind: git
        path: ""
        tag: ""
        url: https://github.com/jortel/hack.git
manifest:
    docker:
        image: nginxinc/nginx-unprivileged:1.23.2
    healthCheck:
        endpoint: ""
        interval: 0
        timeout: 0
        type: ""
    instances: 1
    name: nginx
    port: 8000
    processes:
        - command: /docker-entrypoint.sh nginx -g daemon off;
          disk: "1024"
          healthCheck:
            endpoint: /
            interval: 30
            timeout: 1
            type: port
          instances: 1
          lifecycle: docker
          logRateLimit: "-1"
          memory: "256"
          readinessCheck:
            endpoint: /
            interval: 30
            timeout: 1
            type: process
          type: web
    readinessCheck:
        endpoint: ""
        interval: 0
        timeout: 0
        type: ""
    routes:
        routes:
            - options: {}
              protocol: http1
              route: nginx.bosh-lite.com
    space: space
    timeout: 60
tags:
    - 3rd party=Apache Aries
    - 3rd party=Spring Boot
